# Generated by Django 5.2.7 on 2025-10-24 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('concluido', 'Concluído')], default='pendente', max_length=30)),
                ('titulo', models.CharField(max_length=70)),
                ('nome_do_recebedor', models.CharField(max_length=30)),
                ('valor', models.FloatField()),
                ('descricao', models.TextField()),
                ('data_de_pagamento', models.DateField()),
                ('data_de_criacao', models.DateField()),
                ('anexo', models.FileField(blank=True, null=True, upload_to='anexos/')),
                ('tempo_criacao', models.TimeField()),
                ('tempo_fila', models.TimeField()),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='baixa', max_length=20)),
                ('servico', models.CharField(choices=[('consultoria_TI', 'Consultoria em TI'), ('desenvolvimento', 'Desenvolvimento de Software'), ('manutencao_equipamentos', 'Manutenção de Equipamentos'), ('treinamento_corporativo', 'Treinamento Corporativo')], default='consultoria_TI', max_length=30)),
                ('nome_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
