# Generated by Django 5.2.7 on 2025-10-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacoes',
            name='ticket',
            field=models.CharField(default=0, max_length=25),
        ),
    ]
