# Generated by Django 5.2.7 on 2025-10-31 11:36

import django.db.models.deletion
from django.db import migrations, models


def limpar_servicos_antigos(apps, schema_editor): # type: ignore
    """
    Limpa os valores antigos do campo servico antes de converter para ForeignKey.
    Os valores antigos eram strings como 'consultoria_TI', agora será ForeignKey.
    """
    with schema_editor.connection.cursor() as cursor:
        # Atualizar todos os registros para ter servico = NULL
        # SQLite aceita NULL mesmo em campos CharField que permitem NULL
        cursor.execute(
            "UPDATE solicitacoes_solicitacoes SET servico = NULL"
        )


def reverter_limpeza(apps, schema_editor): # type: ignore
    """
    Função reversa - não faz nada pois não podemos recuperar os valores antigos
    """
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('servicos', '0001_initial'),
        ('solicitacoes', '0002_solicitacoes_ticket'),
    ]

    operations = [
        migrations.RunPython(limpar_servicos_antigos, reverter_limpeza),
        migrations.AlterField(
            model_name='solicitacoes',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicos.servico', verbose_name='Serviço'),
        ),
    ]
