# Generated by Django 5.2.7 on 2025-10-31 11:36

import django.db.models.deletion
from django.db import migrations, models


def limpar_servicos_antigos(apps, schema_editor):
    """
    Limpa os valores antigos do campo servico antes de converter para ForeignKey.
    Os valores antigos eram strings como 'consultoria_TI', agora será ForeignKey.
    """
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Atualizar todos os registros para ter servico = NULL
        # SQLite aceita NULL mesmo em campos CharField que permitem NULL
        cursor.execute(
            "UPDATE solicitacoes_solicitacoes SET servico = NULL"
        )


def reverter_limpeza(apps, schema_editor):
    """
    Função reversa - não faz nada pois não podemos recuperar os valores antigos
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
        ('solicitacoes', '0002_solicitacoes_ticket'),
    ]

    operations = [
        # Primeiro, alterar o CharField para permitir NULL e blank
        migrations.AlterField(
            model_name='solicitacoes',
            name='servico',
            field=models.CharField(blank=True, max_length=30, null=True, choices=[
                ('consultoria_TI', 'Consultoria em TI'),
                ('desenvolvimento', 'Desenvolvimento de Software'),
                ('manutencao_equipamentos', 'Manutenção de Equipamentos'),
                ('treinamento_corporativo', 'Treinamento Corporativo'),
            ]),
        ),
        # Segundo, limpar os valores antigos
        migrations.RunPython(limpar_servicos_antigos, reverter_limpeza),
        # Terceiro, alterar de CharField para ForeignKey
        migrations.AlterField(
            model_name='solicitacoes',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicos.servico', verbose_name='Serviço'),
        ),
    ]

