# Generated by Django 5.2.7 on 2025-10-31 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
        ('solicitacoes', '0003_alter_solicitacoes_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacoes',
            name='tipo',
            field=models.CharField(choices=[('casual', 'Casual'), ('em_rota', 'Em Rota')], default='casual', max_length=20, verbose_name='Tipo de Solicitação'),
        ),
        migrations.CreateModel(
            name='SolicitacaoRotaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_item', models.CharField(max_length=25, verbose_name='ID da Solicitação')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('ordem', models.IntegerField(default=1, verbose_name='Ordem')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicos.servico', verbose_name='Serviço')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_rota', to='solicitacoes.solicitacoes')),
            ],
            options={
                'verbose_name': 'Item da Rota',
                'verbose_name_plural': 'Itens da Rota',
                'ordering': ['ordem'],
            },
        ),
    ]
