# Generated by Django 5.2.7 on 2025-11-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0004_solicitacoes_tipo_solicitacaorotaitem'),
    ]

    operations = [
        # Adicionar campos de valores detalhados ao modelo Solicitacoes
        migrations.AddField(
            model_name='solicitacoes',
            name='valor_km',
            field=models.FloatField(default=0.0, verbose_name='Valor KM'),
        ),
        migrations.AddField(
            model_name='solicitacoes',
            name='valor_pedagio',
            field=models.FloatField(default=0.0, verbose_name='Valor Pedagio'),
        ),
        migrations.AddField(
            model_name='solicitacoes',
            name='valor_hospedagem',
            field=models.FloatField(default=0.0, verbose_name='Valor Hospedagem'),
        ),
        migrations.AddField(
            model_name='solicitacoes',
            name='valor_fluvial',
            field=models.FloatField(default=0.0, verbose_name='Valor Fluvial'),
        ),
        migrations.AddField(
            model_name='solicitacoes',
            name='valor_outros',
            field=models.FloatField(default=0.0, verbose_name='Valor Outros'),
        ),
        migrations.AddField(
            model_name='solicitacoes',
            name='valor_receita',
            field=models.FloatField(default=0.0, verbose_name='Valor de Receita'),
        ),
        # Adicionar campos de valores detalhados ao modelo SolicitacaoRotaItem
        migrations.AddField(
            model_name='solicitacaorotaitem',
            name='valor_km',
            field=models.FloatField(default=0.0, verbose_name='Valor KM'),
        ),
        migrations.AddField(
            model_name='solicitacaorotaitem',
            name='valor_pedagio',
            field=models.FloatField(default=0.0, verbose_name='Valor Pedagio'),
        ),
        migrations.AddField(
            model_name='solicitacaorotaitem',
            name='valor_hospedagem',
            field=models.FloatField(default=0.0, verbose_name='Valor Hospedagem'),
        ),
        migrations.AddField(
            model_name='solicitacaorotaitem',
            name='valor_fluvial',
            field=models.FloatField(default=0.0, verbose_name='Valor Fluvial'),
        ),
        migrations.AddField(
            model_name='solicitacaorotaitem',
            name='valor_outros',
            field=models.FloatField(default=0.0, verbose_name='Valor Outros'),
        ),
    ]

