# Generated by Django 5.2.7 on 2025-11-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0005_add_valores_detalhados'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacoes',
            name='data_entrada_status',
            field=models.DateTimeField(auto_now_add=True, blank=True, null=True, verbose_name='Data de Entrada no Status Atual'),
        ),
        migrations.AddField(
            model_name='solicitacoes',
            name='valor_em_rota',
            field=models.FloatField(default=0.0, verbose_name='Valor EM ROTA'),
        ),
        migrations.AddField(
            model_name='solicitacoes',
            name='descricao_em_rota',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Pagamento EM ROTA'),
        ),
    ]

