# Generated by Django 5.2.7 on 2025-11-06 14:15

from django.db import migrations, models


def ensure_unique_tickets(apps, schema_editor):
    Solicitacoes = apps.get_model('solicitacoes', 'Solicitacoes')
    seen = {}

    for sol_id, ticket in Solicitacoes.objects.order_by('id').values_list('id', 'ticket'):
        if not ticket:
            continue

        count = seen.get(ticket, 0)
        if count == 0:
            seen[ticket] = 1
            continue

        count += 1
        seen[ticket] = count

        suffix = f"-{count}"
        base_length = 25 - len(suffix)
        sanitized = (ticket or '')[:base_length]
        new_ticket = f"{sanitized}{suffix}"

        Solicitacoes.objects.filter(id=sol_id).update(ticket=new_ticket)


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0006_add_data_entrada_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recebedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Recebedor')),
                ('chave_pix', models.CharField(max_length=255, verbose_name='Chave PIX')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Recebedor',
                'verbose_name_plural': 'Recebedores',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='solicitacaorotaitem',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave PIX'),
        ),
        migrations.AddField(
            model_name='solicitacaorotaitem',
            name='recebedor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Recebedor'),
        ),
        migrations.RunPython(ensure_unique_tickets, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='solicitacoes',
            name='ticket',
            field=models.CharField(help_text='ID único da solicitação (Ex: INC001, ROTA-002)', max_length=25, unique=True),
        ),
    ]
