# Generated by Django 5.2.7 on 2025-11-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0007_recebedor_solicitacaorotaitem_chave_pix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome do Cliente/Empresa')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Cliente/Empresa',
                'verbose_name_plural': 'Clientes/Empresas',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='recebedor',
            options={'ordering': ['supervisor', 'nome'], 'verbose_name': 'Recebedor', 'verbose_name_plural': 'Recebedores'},
        ),
        migrations.AddField(
            model_name='recebedor',
            name='supervisor',
            field=models.CharField(blank=True, choices=[('supervisor1', 'Supervisor 1'), ('supervisor2', 'Supervisor 2')], max_length=50, null=True, verbose_name='Supervisor'),
        ),
        migrations.AddField(
            model_name='solicitacaorotaitem',
            name='cliente_empresa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cliente/Empresa'),
        ),
        migrations.AddField(
            model_name='solicitacaorotaitem',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='solicitacoes',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave PIX'),
        ),
        migrations.AddField(
            model_name='solicitacoes',
            name='cliente_empresa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cliente/Empresa'),
        ),
        migrations.AddField(
            model_name='solicitacoes',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ'),
        ),
    ]
