# Generated by Django 5.2.7 on 2025-11-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0008_clienteempresa_alter_recebedor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recebedor',
            name='supervisor',
            field=models.CharField(blank=True, choices=[('supervisor1', 'Nayron Januario'), ('supervisor2', 'Flavio Medina')], max_length=50, null=True, verbose_name='Supervisor'),
        ),
    ]
