# Generated by Django 5.2.7 on 2025-11-25 16:16

from django.db import migrations, models
from django.db.models import F


def preencher_data_aprovacao(apps, schema_editor):
    Solicitacoes = apps.get_model('solicitacoes', 'Solicitacoes')
    Solicitacoes.objects.filter(
        status='aprovado',
        data_aprovacao__isnull=True,
        data_entrada_status__isnull=False
    ).update(data_aprovacao=F('data_entrada_status'))


def remover_data_aprovacao(apps, schema_editor):
    Solicitacoes = apps.get_model('solicitacoes', 'Solicitacoes')
    Solicitacoes.objects.filter(status='aprovado').update(data_aprovacao=None)


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0009_alter_recebedor_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacoes',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação'),
        ),
        migrations.RunPython(preencher_data_aprovacao, remover_data_aprovacao),
    ]
