# Generated by Django 5.2.7 on 2026-02-18 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0016_auditoria_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoes',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('concluido', 'Concluído'), ('estorno', 'Estorno')], default='pendente', max_length=30),
        ),
        migrations.CreateModel(
            name='EstornoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('concluido', 'Concluído'), ('estorno', 'Estorno')], max_length=30, verbose_name='Status Anterior')),
                ('status_novo', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('concluido', 'Concluído'), ('estorno', 'Estorno')], default='estorno', max_length=30, verbose_name='Status Novo')),
                ('origem', models.CharField(blank=True, max_length=255, null=True, verbose_name='Origem')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_estorno', to='solicitacoes.solicitacoes', verbose_name='Solicitação')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de Estorno',
                'verbose_name_plural': 'Histórico de Estornos',
                'ordering': ['-data_hora'],
            },
        ),
    ]
