# Generated by Django 5.2.7 on 2026-02-18 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0017_alter_solicitacoes_status_estornohistorico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacoes',
            name='data_exclusao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão'),
        ),
        migrations.AddField(
            model_name='solicitacoes',
            name='excluida',
            field=models.BooleanField(default=False, verbose_name='Excluída'),
        ),
        migrations.AddField(
            model_name='solicitacoes',
            name='excluida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_excluidas', to=settings.AUTH_USER_MODEL, verbose_name='Excluída por'),
        ),
        migrations.CreateModel(
            name='SolicitacaoExcluida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=25, verbose_name='Ticket')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('concluido', 'Concluído'), ('estorno', 'Estorno')], max_length=30, verbose_name='Status')),
                ('tipo', models.CharField(choices=[('casual', 'Casual'), ('em_rota', 'Em Rota')], max_length=20, verbose_name='Tipo')),
                ('origem', models.CharField(blank=True, max_length=255, null=True, verbose_name='Origem')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo')),
                ('dados_snapshot', models.JSONField(blank=True, null=True, verbose_name='Snapshot')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arquivo_exclusao', to='solicitacoes.solicitacoes', verbose_name='Solicitação')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que excluiu')),
            ],
            options={
                'verbose_name': 'Solicitação Excluída',
                'verbose_name_plural': 'Solicitações Excluídas',
                'ordering': ['-data_hora'],
            },
        ),
    ]
