# Generated by Django 5.2.7 on 2026-02-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0018_solicitacoes_soft_delete_solicitacaoexcluida'),
    ]

    operations = [
        migrations.AddField(
            model_name='estornohistorico',
            name='justificativa',
            field=models.TextField(default='', verbose_name='Justificativa'),
            preserve_default=False,
        ),
    ]
