# Generated by Django 5.2.7 on 2026-03-05 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0019_estornohistorico_justificativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaorotaitem',
            name='recebedor_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_rota', to='solicitacoes.recebedor', verbose_name='Recebedor'),
        ),
        migrations.AddField(
            model_name='solicitacoes',
            name='recebedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_principal', to='solicitacoes.recebedor', verbose_name='Recebedor'),
        ),
        migrations.AlterField(
            model_name='solicitacaorotaitem',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave PIX (legado)'),
        ),
        migrations.AlterField(
            model_name='solicitacaorotaitem',
            name='recebedor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Recebedor (legado)'),
        ),
        migrations.AlterField(
            model_name='solicitacoes',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave PIX (legado)'),
        ),
        migrations.AlterField(
            model_name='solicitacoes',
            name='nome_do_recebedor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Recebedor (legado)'),
        ),
    ]
