# Generated by Django 5.2.7 on 2026-03-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0020_add_recebedor_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorialog',
            name='solicitacao_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID da Solicitação relacionada'),
        ),
        migrations.AlterField(
            model_name='auditorialog',
            name='acao',
            field=models.CharField(choices=[('create', 'Criar'), ('update', 'Atualizar'), ('delete', 'Deletar'), ('login', 'Login')], max_length=20, verbose_name='Ação'),
        ),
    ]
